Revert "Separate auto switch logic from phone switcher"
Breaks current QSSI14 blobs

12-25 01:55:29.231  2978  2978 E AndroidRuntime: Process: com.android.phone, PID: 2978
12-25 01:55:29.231  2978  2978 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method displayAutoDataSwitchNotification()V in class Lcom/qualcomm/qti/internal/telephony/data/QtiPhoneSwitcher; or its super classes (declaration of 'com.qualcomm.qti.internal.telephony.data.QtiPhoneSwitcher' appears in /system_ext/framework/qti-telephony-common.jar)
12-25 01:55:29.231  2978  2978 E AndroidRuntime: 	at com.qualcomm.qti.internal.telephony.data.QtiPhoneSwitcher.onDdsSwitchResponse(QtiPhoneSwitcher.java:457)
12-25 01:55:29.231  2978  2978 E AndroidRuntime: 	at com.android.internal.telephony.data.PhoneSwitcher.handleMessage(PhoneSwitcher.java:824)
12-25 01:55:29.231  2978  2978 E AndroidRuntime: 	at com.qualcomm.qti.internal.telephony.data.QtiPhoneSwitcher.handleMessage(QtiPhoneSwitcher.java:371)
12-25 01:55:29.231  2978  2978 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-25 01:55:29.231  2978  2978 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
12-25 01:55:29.231  2978  2978 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
12-25 01:55:29.231  2978  2978 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8240)
12-25 01:55:29.231  2978  2978 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-25 01:55:29.231  2978  2978 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
12-25 01:55:29.231  2978  2978 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)

This reverts commit 410eaf7a159eccef8d1f4dbd9a332a00d2a39af7.

Change-Id: Ibd7d303da55ea0f53501ae14164324508c802027